const MESSAGES = {
    // Authentication
    1001: 'User registered successfully',
    1002: 'Login successful',
    1003: 'Logged out successfully',
    1004: 'OTP sent to your email successfully',
    1005: 'Email verified successfully',
    1006: 'Password changed successfully',
    1008: 'Business updated successfully',
    1009: 'Business deleted successfully',

    1007: 'Business created succesfully',
    1010: 'Category created successfully',
    1011: 'Categories retrieved successfully',
    1012: 'Category retrieved successfully',
    1013: 'Category updated successfully',
    1014: 'Category deleted successfully',
    1020: 'Home banner created successfully',
    1021: 'Home banners retrieved successfully',
    1022: 'Home banner retrieved successfully',
    1023: 'Home banner updated successfully',
    1024: 'Home banner deleted successfully',

    1025: 'Business retrieved successfully',
    1026: 'Business not found',
    1027: 'Business already exists for this user',
    1028: 'Required fields missing(start date,end date,user_id,location,latitude,longitude,city)',
    1029: 'Create advertise banner request succesfully',
    1030: 'Advertise request not found',
    1031: 'Get advertise banner request succesfully',
    1032: 'Advertise banner not found',
    1033: 'Update advertise banner request succesfully',

    1034: "Offer created successfully",
    1035: "Offers retrieved successfully",
    1036: "Offer retrieved successfully",
    1037: "Offer updated successfully",
    1038: "Offer deleted successfully",
    1039: "Offer not found",
    1040: "Offer can only be updated if status is pending",
    1041: "Required fields missing",
    1042: "Invalid status. Must be one of: pending, approve, reject",
    1043: "Offer status updated successfully",
    1044: "Access denied. Admin role required",
    1045: 'Invalid date range provided',
    1046: 'Maximum 7 approved banners allowed for this location and time period',

    1047: 'Payment method is required when payment details are provided',
    1048: 'Invalid payment method',
    1049: 'Check number is required for check payments',
    1050: 'Transaction ID is required for card/online payments',

    1051: 'Banners fetched successfully',
    1052: 'Slot is not available',
    1053: 'User not authenticated',
    1054: 'offer_id and rating fields missing',
    1055: 'Rating must be between 1-5',
    1056: 'User has already rated this offer',
    1057: 'Rating add successfully',
    1058: 'Get rating successfully',
    1059: 'You are authorized',
    1060: 'Update rating successfully',
    1061: 'Rating deleted successfully',
    1062: 'Image are required',
    1063: 'Users not found',
    1064: 'User retrieved successfully',
    1065: 'Notification not found',
    1066: 'Notification retrieved successfully',
    1067: 'first_name,last_name,email,phone_number,note are required',
    1068: 'Contact us created successfully',
    1069: 'Contact us retrieved successfully',
    1070: 'Contact us not found',
    1071: 'Get all city successfully',
    1072: 'Branch not found',
    1073: 'Business not found',
    1074: 'Missing offer_id parameter',
    1075: 'Offer blocked successfully',
    1076: 'Offer unblocked successfully',
    1077: 'Offer is blocked',
    1078: 'Type parameter is required (branch or business)',



    // Error messages
    2001: 'Email and password are required',
    2002: 'Invalid email or password',
    2003: 'Account is blocked. Please contact support.',
    2004: 'User with this email already exists',
    2005: 'Email, password, and role are required',
    2006: 'Token required for logout',
    2007: 'Session not found',
    2008: 'Invalid or expired token',
    2009: 'Session expired or invalid',
    2010: 'Access token required',
    2011: 'Please verify your email first',
    2012: 'Invalid OTP',
    2013: 'OTP expired',
    2014: 'Email not found',
    2015: 'OTP already sent. Please wait before requesting again',
    2016: 'New password and confirm password do not match',
    2017: 'Password must be at least 8 characters long',
    2018: 'Invalid role. Must be one of: admin, user, business-owner',
    2019: 'Category name is required',
    2020: 'Category not found',
    2021: 'old password, New password and confirm password are required',
    2022: 'old password is not match',
    2023: 'File too large. Maximum size is 5MB.',
    2024: 'Unexpected file field.',
    2025: 'Only image files are allowed!',
    2026: "We couldn't find an account with this email address.",
    2027: "Incorrect password. Please check and try again.",
    2999: 'Internal server error',

    5001: "Create branch successfully",
    5002: "Branch with this name already exist",
    5003: "Branch deleted successfully",
    5004: "Cannot delete the last branch",
    5005: "Please add business for this user",
    5006: "Business image deleted successfully",
    5007: "Business Image not found",
    5008: "You are not admin",
    5009: "Send unblock user request successfully",
    5010: "Get decline reason list successfully",
    5011: "Business owner block successfully",

    // Settings
    5012: 'Settings retrieved successfully',
    5013: 'Setting added successfully',
    5014: 'Setting updated successfully',
    5015: 'Setting deleted successfully',
    5016: 'Setting not found',
    5017: 'Setting key is required',
    5018: 'Setting value is required',
    5019: "Branches retrieved successfully",
    5020: 'Business ID is required',
    5021: "Nearby offers retrieved successfully",
    5022: "Update branch data successfully",
    5033: "Get profile data successfully",
    5034: "Id not found",
    5035: 'Latitude and longitude are required',
    5036: "Profile updated successfully",
    5037: "Offer report created successfully",
    5038: "Offer reports retrieved successfully",
    5039: "Get dashboard successfully",
    5040: "User verify successfully",
    5041: "User already verify",
    5042: "Unblock request already exists and is pending for this user",
    5042: "Notification send successfully",
    5043: "Notification read successfully",
    5044: "Advertise request deleted successfully",
    5055: "You have not registered for this role.",
    5056: "Admin role not found",
    5057: "User not found",
    5058: "Admin deleted successfully",
    5059: "Content not added by admin",
    5060: "We have emailed you a password reset link. Please check your inbox and spam folder.",
    5070: "This business is alredy ragister",
    5071: "User delete succesfully",
    5072: "Offer report succesfully",
    5073: "Get offer reports succesfully",
    5074: "Page and Limit is required",
    5075: "Please select the role",
    5076: "You already sent unblock request. it's pending from admin side"
};

const get_message = message_code => {
    if (isNaN(message_code)) {
        return message_code;
    }
    return message_code ? MESSAGES[message_code] : message_code;
};

export { get_message };